apiVersion: v1
kind: Service
metadata:
  name: finalproject-service
spec:
  selector:
    app: finalproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort 
